// Mocks generated by Mockito 5.4.6 from annotations
// in catinder/test/main.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:catinder/domain/entity/cat.dart' as _i6;
import 'package:catinder/domain/repositories/cat_repository.dart' as _i3;
import 'package:catinder/domain/repositories/local_repository.dart' as _i2;
import 'package:catinder/domain/usecases/delete_liked_cat_usecase.dart' as _i7;
import 'package:catinder/domain/usecases/fetch_cats_usecase.dart' as _i8;
import 'package:catinder/domain/usecases/get_liked_cats_usecase.dart' as _i4;
import 'package:catinder/domain/usecases/save_liked_cat_usecase.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocalRepository_0 extends _i1.SmartFake
    implements _i2.LocalRepository {
  _FakeLocalRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCatRepository_1 extends _i1.SmartFake implements _i3.CatRepository {
  _FakeCatRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetLikedCatsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLikedCatsUseCase extends _i1.Mock
    implements _i4.GetLikedCatsUseCase {
  MockGetLikedCatsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLocalRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.LocalRepository);

  @override
  _i5.Future<List<_i6.LikedCat>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i5.Future<List<_i6.LikedCat>>.value(<_i6.LikedCat>[]),
          )
          as _i5.Future<List<_i6.LikedCat>>);
}

/// A class which mocks [DeleteLikedCatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteLikedCatUseCase extends _i1.Mock
    implements _i7.DeleteLikedCatUseCase {
  MockDeleteLikedCatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLocalRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.LocalRepository);

  @override
  _i5.Future<void> execute(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [FetchCatsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchCatsUseCase extends _i1.Mock implements _i8.FetchCatsUseCase {
  MockFetchCatsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCatRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.CatRepository);

  @override
  _i5.Future<List<_i6.Cat>> execute({int? limit = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {#limit: limit}),
            returnValue: _i5.Future<List<_i6.Cat>>.value(<_i6.Cat>[]),
          )
          as _i5.Future<List<_i6.Cat>>);
}

/// A class which mocks [SaveLikedCatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveLikedCatUseCase extends _i1.Mock
    implements _i9.SaveLikedCatUseCase {
  MockSaveLikedCatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLocalRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.LocalRepository);

  @override
  _i5.Future<void> execute(_i6.LikedCat? cat) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [cat]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
