name: catinder
description: "Like tinder, but better, because there are cats."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  http: ^1.3.0
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/kitty.png"